### ISSUE TITLE
Needs a release

### ISSUE THREAD

**Issue by knownasilya** [denali-js/denali-cli#58]
🚀 (maybe after merging a few PRs 😉)

**Comment by davewasmer** [comment]
I'd like to get this on semantic release. PR's welcome ;)

**Comment by knownasilya** [comment]
Is there a past PR in another project I can copy?

**Comment by davewasmer** [comment]
Not handy, but the semantic-release docs / CLI are pretty awesome at running through the process

**Comment by davewasmer** [comment]
Derp. It's on semantic release already.
